/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GovCreateProblemRouteImport } from './routes/gov.create-problem'
import { Route as GovDashboardRouteImport } from './routes/gov.dashboard'
import { Route as GovProblemsRouteImport } from './routes/gov.problems'
import { Route as GovStructuringRouteImport } from './routes/gov.structuring'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GovCreateProblemRoute = GovCreateProblemRouteImport.update({
  id: '/gov/create-problem',
  path: '/gov/create-problem',
  getParentRoute: () => rootRouteImport,
} as any)
const GovDashboardRoute = GovDashboardRouteImport.update({
  id: '/gov/dashboard',
  path: '/gov/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GovProblemsRoute = GovProblemsRouteImport.update({
  id: '/gov/problems',
  path: '/gov/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const GovStructuringRoute = GovStructuringRouteImport.update({
  id: '/gov/structuring',
  path: '/gov/structuring',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gov/create-problem': typeof GovCreateProblemRoute
  '/gov/dashboard': typeof GovDashboardRoute
  '/gov/problems': typeof GovProblemsRoute
  '/gov/structuring': typeof GovStructuringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gov/create-problem': typeof GovCreateProblemRoute
  '/gov/dashboard': typeof GovDashboardRoute
  '/gov/problems': typeof GovProblemsRoute
  '/gov/structuring': typeof GovStructuringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gov/create-problem': typeof GovCreateProblemRoute
  '/gov/dashboard': typeof GovDashboardRoute
  '/gov/problems': typeof GovProblemsRoute
  '/gov/structuring': typeof GovStructuringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gov/create-problem'
    | '/gov/dashboard'
    | '/gov/problems'
    | '/gov/structuring'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gov/create-problem'
    | '/gov/dashboard'
    | '/gov/problems'
    | '/gov/structuring'
  id:
    | '__root__'
    | '/'
    | '/gov/create-problem'
    | '/gov/dashboard'
    | '/gov/problems'
    | '/gov/structuring'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GovCreateProblemRoute: typeof GovCreateProblemRoute
  GovDashboardRoute: typeof GovDashboardRoute
  GovProblemsRoute: typeof GovProblemsRoute
  GovStructuringRoute: typeof GovStructuringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gov/create-problem': {
      id: '/gov/create-problem'
      path: '/gov/create-problem'
      fullPath: '/gov/create-problem'
      preLoaderRoute: typeof GovCreateProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gov/dashboard': {
      id: '/gov/dashboard'
      path: '/gov/dashboard'
      fullPath: '/gov/dashboard'
      preLoaderRoute: typeof GovDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gov/problems': {
      id: '/gov/problems'
      path: '/gov/problems'
      fullPath: '/gov/problems'
      preLoaderRoute: typeof GovProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gov/structuring': {
      id: '/gov/structuring'
      path: '/gov/structuring'
      fullPath: '/gov/structuring'
      preLoaderRoute: typeof GovStructuringRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GovCreateProblemRoute: GovCreateProblemRoute,
  GovDashboardRoute: GovDashboardRoute,
  GovProblemsRoute: GovProblemsRoute,
  GovStructuringRoute: GovStructuringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
